### ISSUE TITLE
create html output

### ISSUE THREAD

**Issue by davisaqueen** [koresar/s3-tree#4]
is it possible to add a cli argument to create html tree view from result?

**Comment by koresar** [comment]
Everything is possible. But what is "html tree view" in your case?

**Comment by davisaqueen** [comment]
rendering the result and save it as a collapsable html tree design.

**Comment by koresar** [comment]
This is a simple 1-function module. Generating  files with HTML structure in it sounds like an overkill.

It's kind of a feature only you need. I'm happy to reconsider if there are many similar requests.
